# Generated by Django 5.0.4 on 2024-09-23 16:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('data_cadastro', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('codigo_barras', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensoes', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.IntegerField(blank=True, null=True)),
                ('nf', models.IntegerField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_pg', models.DateField(blank=True, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=5, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('frete', models.CharField(blank=True, max_length=3, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('forma_pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.forma_pg')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa_aberto', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalizado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa_aberto', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('valor_uni', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finalizado', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.IntegerField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_pg', models.DateField(blank=True, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=5, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete', models.CharField(blank=True, max_length=3, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente')),
                ('forma_pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.forma_pg')),
            ],
        ),
    ]
