# Generated by Django 5.0.4 on 2024-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_caixa_compra_produto_alter_caixa_venda_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa_venda',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
