# Generated by Django 5.0.4 on 2025-01-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_atividade_fornecedor_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='caixa_compra',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='caixa_venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produtos_1',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='forma_pg',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='forma_pg',
        ),
        migrations.RemoveField(
            model_name='produtos_1',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.RemoveField(
            model_name='produtos_1',
            name='unidade_medida',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Caixa_compra',
        ),
        migrations.DeleteModel(
            name='Caixa_venda',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Forma_PG',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Produtos_1',
        ),
        migrations.DeleteModel(
            name='Unidade_medida',
        ),
    ]
