# Generated by Django 5.0.4 on 2025-01-10 01:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('cod_produto', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('codigo_barras', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensoes', models.CharField(blank=True, max_length=10, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.marca')),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtos')),
            ],
        ),
    ]
