# Generated by Django 5.0.4 on 2025-01-10 01:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_categoria_tiposervicos_unidademedida_produtos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('whatsapp', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contas_receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_finalizacao', models.DateTimeField(default=datetime.datetime.now)),
                ('parcela', models.CharField(max_length=10)),
                ('forma_pg', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateTimeField()),
                ('obs', models.CharField(max_length=50)),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contas_a_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_finalizacao', models.DateTimeField(default=datetime.datetime.now)),
                ('parcela', models.CharField(max_length=10)),
                ('forma_pg', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateTimeField()),
                ('obs', models.CharField(max_length=50)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='OS_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('whatsapp', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.tiposervicos')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.veiculos')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.profissional')),
            ],
        ),
    ]
