# Generated by Django 5.0.4 on 2025-01-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_cargo_fornecedor_status_contas_receber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa_compra',
            old_name='status',
            new_name='finalizado',
        ),
        migrations.RenameField(
            model_name='caixa_compra',
            old_name='desconto',
            new_name='valor_uni',
        ),
        migrations.RemoveField(
            model_name='caixa_compra',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='caixa_compra',
            name='os',
        ),
        migrations.AddField(
            model_name='caixa_compra',
            name='caixa_aberto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
