# Generated by Django 5.0.4 on 2025-01-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_rename_status_caixa_compra_finalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.IntegerField(blank=True, null=True)),
                ('nf', models.IntegerField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('forma_pg', models.CharField(max_length=10)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_pg', models.DateField(blank=True, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=5, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('frete', models.CharField(blank=True, max_length=3, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.fornecedor')),
            ],
        ),
    ]
