# Generated by Django 5.0.4 on 2025-01-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
    ]
