# Generated by Django 5.0.4 on 2025-01-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_marcaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.marcaproduto'),
        ),
    ]
