# Generated by Django 5.0.4 on 2025-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
