# Generated by Django 5.0.4 on 2025-01-15 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_alter_veiculos_transmissao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa_compra',
            old_name='finalizado',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='caixa_compra',
            name='caixa_aberto',
        ),
        migrations.AddField(
            model_name='caixa_compra',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='caixa_compra',
            name='os',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='os',
            name='obs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
