# Generated by Django 5.0.4 on 2025-01-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_rename_finalizado_caixa_compra_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_a_pagar',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='data_chegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='data_pg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='frete',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='nf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contas_a_pagar',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
