# Generated by Django 5.0.4 on 2025-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_contas_a_pagar_acrescimo_contas_a_pagar_data_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_receber',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contas_receber',
            name='data_pg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contas_receber',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
