# Generated by Django 5.0.4 on 2025-01-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_contas_receber_acrescimo_contas_receber_data_pg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
