# Generated by Django 5.0.4 on 2025-01-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_profissional_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Folha_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('datas', models.DateTimeField()),
                ('obs', models.CharField(max_length=50)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.profissional')),
            ],
        ),
    ]
