# Generated by Django 5.0.4 on 2025-01-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_dias_uteis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dias_uteis',
            name='Dias_uteis',
        ),
        migrations.AddField(
            model_name='profissional',
            name='quant_passagens_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dias_uteis',
            name='dias_uteis',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
