# Generated by Django 5.0.4 on 2025-01-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_remove_dias_uteis_dias_uteis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dias_uteis',
            old_name='dias_uteis',
            new_name='quant_dias',
        ),
    ]
