# Generated by Django 5.0.4 on 2025-01-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0029_rename_dias_uteis_dias_uteis_quant_dias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='quant_passagens_dia',
            new_name='passagens_dia',
        ),
    ]
