# Generated by Django 5.0.4 on 2025-01-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0030_rename_quant_passagens_dia_profissional_passagens_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='passagens_dia',
            new_name='vt_diario',
        ),
    ]
