# Generated by Django 5.0.4 on 2025-02-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0031_rename_passagens_dia_profissional_vt_diario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folha_pagamento',
            old_name='descontos',
            new_name='desconto_vt',
        ),
        migrations.RemoveField(
            model_name='folha_pagamento',
            name='datas',
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='dia_extras',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='fgts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='mes_ano_competencia',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='pg_salario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='pg_va_vt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='va',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='vt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folha_pagamento',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
