# Generated by Django 5.0.4 on 2025-02-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_rename_descontos_folha_pagamento_desconto_vt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folha_pagamento',
            old_name='dia_extras',
            new_name='dias_extras',
        ),
        migrations.AddField(
            model_name='folha_pagamento',
            name='salario_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
