# Generated by Django 5.0.4 on 2025-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_rename_dia_extras_folha_pagamento_dias_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='valor_no_momento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='os_produto',
            name='valor_no_momento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
