# Generated by Django 5.0.4 on 2025-03-01 05:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0034_os_valor_no_momento_os_produto_valor_no_momento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custos_extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custo', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('parcela', models.CharField(max_length=10)),
                ('forma_pg', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateTimeField()),
                ('data_pg', models.DateField(blank=True, null=True)),
                ('obs', models.CharField(max_length=50)),
                ('usuario', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.fornecedor')),
            ],
        ),
    ]
