# Generated by Django 5.0.4 on 2025-03-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0035_custos_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custos_extras',
            old_name='id_custo',
            new_name='n_caixa',
        ),
    ]
