# Generated by Django 5.0.4 on 2025-03-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0036_rename_id_custo_custos_extras_n_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='custos_extras',
            name='referencia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
