# Generated by Django 5.0.4 on 2025-03-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0037_custos_extras_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_extras',
            name='vencimento',
            field=models.DateField(),
        ),
    ]
