# Generated by Django 5.0.4 on 2025-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0038_alter_custos_extras_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_extras',
            name='data_pg',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='custos_extras',
            name='referencia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custos_extras',
            name='vencimento',
            field=models.DateField(default=''),
        ),
    ]
