# Generated by Django 5.0.4 on 2025-03-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0039_alter_custos_extras_data_pg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custos_extras',
            old_name='n_caixa',
            new_name='n_servico',
        ),
    ]
