# Generated by Django 5.0.4 on 2025-03-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0042_alter_custos_extras_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_extras',
            name='vencimento',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
