# Generated by Django 5.0.4 on 2025-03-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0043_alter_custos_extras_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos_extras',
            name='data_pg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custos_extras',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custos_extras',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
